package com.libraryapp.spring_boot_library.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Data;
import org.hibernate.annotations.CreationTimestamp;

@Entity
@Table(name = "review")
@Data
public class Review {
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "id")
  private Long id;

  //   generate user_email ,date(with Creationtimestamp) rating, bookid and review_description
  @Column(name = "user_email")
  private String userEmail;

  @Column(name = "date")
  @CreationTimestamp
  private String date;

  @Column(name = "rating")
  private int rating;

  @Column(name = "book_id")
  private Long bookId;

  @Column(name = "review_description")
  private String reviewDescription;

  // Getters and Setters can be generated by Lombok's @Data annotation
}
